### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jue89** [lemoer/bpfcountd#3]
Can you think about what license you would like to use for this project?

I would like to use your project in a commercial project if your desired license allows that. In return I want to implement reloading the filter file using a signal.

**Comment by lemoer** [comment]
Is the MIT License ok for your use? I am willing to publish under this license...

However I want to hint you, that you will get more performance if you use iptables chains for your counters. It's not that handy, but it should result in better performance, since the packets do not need to be delivered to the userland. But I think it's only important on realy high performance situations.

**Comment by jue89** [comment]
MIT sounds great!

I just want to count a few packages. And I like the flexibility of BPF :)

**Comment by lemoer** [comment]
I added a license file, so it's clear for future.
